### ISSUE TITLE
Add --follow/-f option to `read` command

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-manager#57]
## Background
- frontend uses `dapp-manager read` command to read the output streams (stderr, stdout, data, state) 
- the command currently looks like this:
```bash
$ dapp-manager read
Usage: dapp-manager read [OPTIONS] COMMAND [ARGS]...

  Read output from the given app.

Options:
  --help  Show this message and exit.

Commands:
  data    Read the data stream of the given app.
  log     Read the log stream of a given app.
  state   Read the state stream of the given app.
  stderr  Read the stderr of a given app.
  stdout  Read the stdout of a given app.
```

## What:
We need a way to continuously stream output without ending the command after reaching end of log file, so that we don't have to receive the whole content each time. In the end the frontend doesn't get whole several MB logs at once.

## Prerequisites:
- [x] @grisha87 will research BE->FE log streaming patters and accept/modify following paragraphs

## How:
 - [ ] add `--follow/f` arg to `read` command that will continuously print new content of log
   - new method in storage class to continuously read log file?

**Comment by mateuszsrebrny** [comment]
@grisha87 does this look convenient for you?

**Comment by grisha87** [comment]
I think using bytes and controlling the lengths will make the use of this extremely difficult. My proposal would be different: lets implement this in a `tail`-like manner, where we can control the number of lines on the output which will be very familiar to the users and might be easier to integrate with other applications. I've invited for a F2F discussion tomorrow :)

**Comment by grisha87** [comment]
Hey guys!

Sorry for keeping you waiting. I managed to take a look at that, and I have a proposal of how we can solve this.

First of all, lets note that we have 2 use-cases:

1. Downloading whole contents of the output (regardless which `read` sub-command this will be)
2. Providing "live updates" to the users of Golem Portal, so that the UI with logs (for example) can be updated in a live manner.

I've analyzed how I would like to shape the UI and API for these use cases, and here's what I got:

## Use Case 1: Downloading full logs

When the user will request the full output for download, we will provide a link to a ZIP file. The ZIP file can be formed by us quite easily:

```bash
dapp-manager read log ac424aed76804ed9b499ddb804544b15 > ac424aed76804ed9b499ddb804544b15.log
zip ac424aed76804ed9b499ddb804544b15-logs.zip ac424aed76804ed9b499ddb804544b15.log
```

Then we can send the file back to the user. I don't think we need to provide the info about the size of the logs on the UI, so lets leave this for now.

## Use Case 2: Streaming logs live

When the user will start the app, we would like to provide live-updates of the content. We want to utilize a event/websocket mechanism which will send live updates from server as they appear. In order to do so, we would like to call the following line:

```bash
dapp-manager read log ac424aed76804ed9b499ddb804544b15 -f | tail -n 20 -f
```

This way we can control the amount of provided logs and also keep the STDIO open to continuously stream the results to the users.

This use-case requires adding support of the `-f, --follow` option to the command so that the dapp-manager process won't exit immediately and keep streaming output. I think that's a great addition for the CLI users and will allow us (Golem Portal) to implement more sophisticated filtering with other UNIX tools, without putting more into dapp-manager.
