### ISSUE TITLE
click dependency version conflict from SCT

### ISSUE THREAD

**Issue by etam** [golemfactory/dapp-manager#77]
when installing `pip install git+https://github.com/golemfactory/dapp-manager.git@main` (where main = fbcfa9590ef9acd89c0c20ff0d4dbf3edbd71d2c) in a clean venv:
```
ERROR: Cannot install dapp-manager and dapp-manager==0.0.0a4 because these package versions have conflicting dependencies.

The conflict is caused by:
    dapp-manager 0.0.0a4 depends on click<9.0 and >=8.1
    dapp-runner 0.0.0a3 depends on click<8.0 and >=7.0
```

**Comment by grisha87** [comment]
Right now we're trying to set up portal.golem.network which is getting dapp-manager and dapp-runner from main branches. I would propose doing a proper release of both apps, so that we get the tags for these releases from you guys and then we can deploy production (+dapp.golem.network) from tags directly. Would be nice to have the resolution by Tuesday next week, because we wanted to start internal tests of the Portal

**Comment by approxit** [comment]
Fixed in https://github.com/golemfactory/dapp-manager/pull/78
